={{ JSON.stringify({
  ref_bien: $json.ref_bien || '',
  hash_structurel: $json.hash_structurel || '',
  hash_tel_bien: $json.hash_tel_bien || '',
  type_de_bien: $json.type_de_bien || '',
  type_offre: $json.type_offre || '',
  zone_geographique: $json.zone_geographique || '',
  commune: $json.commune || '',
  quartier: $json.quartier || '',
  prix: $json.prix || '',
  prix_normalise: $json.prix_normalise || 0,
  surface: $json.surface || '',
  chambre: String($json.chambre || ''),
  meubles: $json.meubles || 'Non',
  caracteristiques: ($json.caracteristiques || '').substring(0, 1000),
  telephone_bien: $json.telephone_bien || '',
  telephone_expediteur: $json.cleanedSenderPn || $json.telephone_expediteur || '',
  expediteur: $json.expediteur || '',
  publie_par: $json.publie_par || '',
  disponible: $json.disponible || 'Oui',
  status: 'active',
  groupe_whatsapp_origine: $json.groupe_whatsapp_origine || '',
  groupe_whatsapp_jid: $json.groupe_whatsapp_jid || '',
  message_initial: ($json.message_initial || '').substring(0, 2000),
  publication_id: $json.publication_id || '',
  date_publication: $json.date_publication || new Date().toISOString(),
  date_expiration: $json.date_expiration || '',
  relance_count: 0,
  lien_image: ''
}) }}